targets:
  $default:
    builders:      
      go_router_builder:
        generate_for:
          - lib/src/core/router/app_router.dart
      freezed:
        generate_for:
          - lib/src/features/**/*.controller.dart
          - lib/src/features/*/domain/entities/*.dart
          - lib/src/core/navigator/default_navigator.controller.dart
          - lib/src/features/*/data/dtos/*.dart
      json_serializable:
        generate_for:
          - lib/src/features/*/domain/entities/*.dart
          - lib/src/features/*/data/dtos/*.dart
      riverpod_generator:
        generate_for:
          - lib/src/features/**/*.controller.dart
          - lib/src/features/*/data/repositories/*.dart
          - lib/src/features/*/providers/*.dart
          - lib/src/features/*/providers/*.dart
          - lib/src/core/network/api_client.dart
          - lib/src/core/utils/visual_logger_provider.dart
          - lib/src/features/notification/domain/push_notification.dart